version: '3'

services:
  mongo:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - /storage/mongo:/data/db
    networks:
      - net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
    links:
      - mongo
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - net
  app:
    image: node:12.3
    volumes:
      - ./app:/app
    ports:
      - 8080:8080 # Servidor
      - 8181:8181 # Debug
    working_dir: /app
    entrypoint: bash ./app.sh
    environment:
      - NODE_ENV=development
      - MONGO_CONNECTION_STRING=mongodb://mongo:mongo@mongo:27017
      - MONGO_DB_NAME=survey-answer
    networks:
      - net
networks: 
    net:
      driver: bridge